_mcreator_prefix: "CUSTOM:"
_mcreator_map_template: "@modid:@registryname"
acacia: savanna_tree
bamboo_some_podzol: bamboo
birch: birch_tree
birch_tall: super_birch_tree
blue_ice: blue_ice
bonus_chest: bonus_chest
chorus_plant: chorus_plant
dark_oak: dark_oak_tree
desert_well: desert_well
disk_clay: disk
disk_grass: disk
disk_gravel: disk
disk_sand: disk
end_gateway_delayed: end_gateway
end_gateway_return: end_gateway
end_island: end_island
end_spike: end_spike
fancy_oak: fancy_tree
flower_default: default_flower
flower_flower_forest: forest_flower
flower_plain: plain_flower
flower_swamp: swamp_flower
forest_flowers: general_forest_flower
forest_rock: forest_rock
fossil_coal: fossil
fossil_diamonds: fossil
freeze_top_layer: freeze_top_layer
glowstone_extra: glowstone_blob
huge_brown_mushroom: huge_brown_mushroom
huge_red_mushroom: huge_red_mushroom
ice_patch: ice_patch
ice_spike: ice_spike
iceberg_blue: iceberg
iceberg_packed: iceberg
jungle_bush: jungle_ground_bush
jungle_tree: jungle_tree
jungle_tree_no_vine: jungle_tree
kelp: kelp
lake_lava: lake
mega_jungle_tree: mega_jungle_tree
mega_pine: mega_pine_tree
mega_spruce: mega_spruce_tree
monster_room: monster_room
oak: normal_tree
ore_andesite: ore
ore_clay: ore
ore_coal: ore
ore_coal_buried: ore
ore_diamond_buried: ore
ore_diamond_large: ore
ore_diamond_small: ore
ore_diorite: ore
ore_dirt: ore
ore_emerald: ore
ore_gold: ore
ore_gold_buried: ore
ore_granite: ore
ore_gravel: ore
ore_gravel_nether: ore
ore_infested: ore
ore_iron: ore
ore_iron_small: ore
ore_lapis: ore
ore_lapis_buried: ore
ore_magma: ore
ore_nether_gold: ore
ore_quartz: ore
ore_redstone: ore
ore_soul_sand: ore
patch_berry_bush: sweet_berry_bush
patch_brown_mushroom: huge_brown_mushroom
patch_cactus: cactus
patch_dead_bush: dead_bush
patch_fire: hell_fire
patch_grass: grass
patch_grass_jungle: jungle_grass
patch_large_fern: decorated_flower
patch_melon: melon
patch_pumpkin: pumpkin
patch_red_mushroom: huge_red_mushroom
patch_sugar_cane: decorated
patch_sunflower: patch_sunflower
patch_taiga_grass: taiga_grass
patch_waterlily: waterlily
pile_hay: hay_pile
pile_ice: ice_pile
pile_melon: melon_pile
pile_pumpkin: pumpkin_pile
pile_snow: snow_pile
pine: pine_tree
sea_pickle: sea_pickle
seagrass_mid: seagrass
seagrass_short: seagrass
seagrass_simple: seagrass
seagrass_slightly_less_short: seagrass
seagrass_tall: seagrass
single_piece_of_grass: grass
spring_lava_frozen: spring_feature
spring_lava_nether: nether_spring
spring_lava_overworld: spring_feature
spring_nether_closed: nether_spring
spring_nether_open: nether_spring
spring_water: spring_feature
spruce: spruce_tree
swamp_oak: swamp_tree
trees_birch_and_oak: birch_tree
trees_flower_forest: normal_tree
trees_jungle: jungle_tree
trees_old_growth_pine_taiga: mega_pine_tree
trees_old_growth_spruce_taiga: mega_spruce_tree
trees_plains: normal_tree
trees_savanna: savanna_tree
trees_sparse_jungle: jungle_tree
trees_taiga: pine_tree
trees_water: coral_tree
trees_windswept_hills: normal_tree
vines: vines
void_start_platform: void_start_platform
